<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DataDrivenTestSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>34c21c8d-343e-4f56-a33f-67c8c0413c35</testSuiteGuid>
   <testCaseLink>
      <guid>2aae934c-9198-449d-b335-f1999ce84574</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/API_Testing/Rest DDT TC</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>b8969b85-64cf-4cd3-8868-07fc4bbb0e17</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/RestDatadriven</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>b8969b85-64cf-4cd3-8868-07fc4bbb0e17</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>8b3380fe-a600-4919-922a-48b7a2a5519d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b8969b85-64cf-4cd3-8868-07fc4bbb0e17</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>desegnation</value>
         <variableId>99f5a638-e6c4-4d82-9a76-80b4f27f9e4b</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
